In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

# 初始化随机森林模型
rf_model = RandomForestRegressor(n_estimators=100, random_state=45)

In [2]:
df_csv = pd.read_csv('df_past_order_with_cluster.csv', index_col=0, parse_dates=True)
df_csv.drop('SKU', axis=1, inplace=True)
#转置
df_csv = df_csv.T
X= df_csv.iloc[:, 0]
train = df_csv.loc['2016-06-01':'2016-06-18']   
test = df_csv.loc['2016-06-18':'2016-06-23']
X_train = df_csv.loc['2016-06-01':'2016-06-18']   
X_test = df_csv.loc['2016-06-18':'2016-06-23']




/tmp/ipykernel_57204/2174509327.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_csv = pd.read_csv('df_past_order_with_cluster.csv', index_col=0, parse_dates=True)


In [3]:
for col in train:
    #从第二列开始 提取每一列数据进行预测
    train_data = train[col]
    test_data = test[col]
    rf_model.fit(X_train, train_data)
    # 使用模型进行预测
    rf_model.fit(X_train, train_data)
    y_pred = rf_model.predict(X_test)
    from sklearn.metrics import mean_squared_error
    print(y_pred)

    print(test_data)
    # 计算MSE
    rmse = np.sqrt(mean_squared_error(y_pred, test_data))

    print(f'RMSE: {rmse}')

[294.522 368.744 363.518 237.755 250.143 243.972]
2016-06-18    293.8
2016-06-19    366.8
2016-06-20    359.4
2016-06-21    232.5
2016-06-22    238.9
2016-06-23    270.3
Name: shang-hai-shi, dtype: float64
RMSE: 12.03080768970512
[31.157 32.723 32.964 26.231 27.004 27.298]
2016-06-18    32.0
2016-06-19    36.5
2016-06-20    33.6
2016-06-21    25.5
2016-06-22    26.3
2016-06-23    26.8
Name: shang-rao-shi, dtype: float64
RMSE: 1.6662760375560004
[118.352 127.288 124.371 102.062 103.084 102.391]
2016-06-18    118.9
2016-06-19    125.4
2016-06-20    120.4
2016-06-21    108.3
2016-06-22    112.2
2016-06-23     88.3
Name: dong-guan-shi, dtype: float64
RMSE: 7.529985281083425
[27.81  38.351 39.564 22.314 22.701 22.617]
2016-06-18    27.0
2016-06-19    36.3
2016-06-20    39.7
2016-06-21    21.6
2016-06-22    19.9
2016-06-23    18.9
Name: dong-ying-shi, dtype: float64
RMSE: 2.123388918686359
[37.905 48.816 49.343 33.642 31.925 33.68 ]
2016-06-18    37.8
2016-06-19    44.4
2016-06-20    50.9
20