In [41]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor




In [42]:
df_csv = pd.read_csv('df_past_order_with_cluster.csv', index_col=0, parse_dates=True)
df_csv.drop('SKU', axis=1, inplace=True)
grouped = df_csv.groupby('Cluster')

# 然后你可以分别访问每个组的数据
group_0 = grouped.get_group(0)
group_1 = grouped.get_group(1)
group_2 = grouped.get_group(2)
group_0=group_0.T
X= df_csv.iloc[:, 0]
train = group_0.loc['2016-06-01':'2016-06-18']   
test = group_0.loc['2016-06-18':'2016-06-23']
X_train = group_0.loc['2016-06-01':'2016-06-18']   
X_test = group_0.loc['2016-06-18':'2016-06-23']

/tmp/ipykernel_50480/2279121638.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_csv = pd.read_csv('df_past_order_with_cluster.csv', index_col=0, parse_dates=True)


In [43]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=85)

In [44]:
sum=0
for col in train:
    #从第二列开始 提取每一列数据进行预测
    train_data = train[col]
    test_data = test[col]
    rf_model.fit(X_train, train_data)
    y_pred = rf_model.predict(X_test)
    from sklearn.metrics import mean_squared_error
    print(y_pred)

    print(test_data)
    # 计算MSE
    rmse = np.sqrt(mean_squared_error(y_pred, test_data))
    sum+=rmse
    print(f'RMSE: {rmse}')

print({sum})
temp=sum/6
print({temp})

[298.599 370.657 371.66  233.118 231.307 287.348]
2016-06-18    293.8
2016-06-19    366.8
2016-06-20    359.4
2016-06-21    232.5
2016-06-22    238.9
2016-06-23    270.3
Name: shang-hai-shi, dtype: float64
RMSE: 9.459424991333677
[494.448 496.426 497.47  368.562 371.217 366.721]
2016-06-18    498.6
2016-06-19    494.4
2016-06-20    523.3
2016-06-21    346.8
2016-06-22    369.0
2016-06-23    373.8
Name: bei-jing-shi, dtype: float64
RMSE: 14.242803176809682
[176.201 223.435 227.829 139.324 145.932 148.617]
2016-06-18    177.7
2016-06-19    228.0
2016-06-20    218.6
2016-06-21    143.2
2016-06-22    145.0
2016-06-23    154.9
Name: tian-jin-shi, dtype: float64
RMSE: 5.2222082813052495
[202.518 248.218 249.248 158.582 167.392 140.277]
2016-06-18    204.1
2016-06-19    232.3
2016-06-20    261.5
2016-06-21    159.6
2016-06-22    169.1
2016-06-23    127.4
Name: guang-zhou-shi, dtype: float64
RMSE: 9.795982756552153
[210.339 247.09  248.942 169.754 165.148 173.221]
2016-06-18    212.2
2016-06-1